//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogInfo
    {
        public int Id { get; set; }
        public long OldSum { get; set; }
        public long NewSum { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
