//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int Id { get; set; }
        public string PostContent { get; set; }
        public string Image { get; set; }
        public string UserId { get; set; }
        public int TopicId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
