//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actior
    {
        public Actior()
        {
            this.Movies = new HashSet<Movy>();
            this.Movies1 = new HashSet<Movy>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
    
        public virtual ICollection<Movy> Movies { get; set; }
        public virtual ICollection<Movy> Movies1 { get; set; }
    }
}
