//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movies.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MoviesMVCEntities : DbContext
    {
        public MoviesMVCEntities()
            : base("name=MoviesMVCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Actior> Actiors { get; set; }
        public DbSet<Movy> Movies { get; set; }
        public DbSet<Studio> Studios { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
