//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlSupermarketModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesure
    {
        public Mesure()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int ID { get; set; }
        public string Mesure_Name { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}
