//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlSupermarketModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.SellsReports = new HashSet<SellsReport>();
        }
    
        public int ID { get; set; }
        public string Product_Name { get; set; }
        public decimal Base_Price { get; set; }
        public int mesures_ID { get; set; }
        public int vendors_ID { get; set; }
    
        public virtual Mesure Mesure { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual ICollection<SellsReport> SellsReports { get; set; }
    }
}
