//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlSupermarketModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellsReport
    {
        public int ID { get; set; }
        public int ProductID { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
