//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostsData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Categories = new HashSet<Category>();
        }
    
        public int Id { get; set; }
        public string PostContent { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
    
        public virtual ICollection<Category> Categories { get; set; }
    }
}
