//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLiteModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsReport
    {
        public long ID { get; set; }
        public string Vendor_Name { get; set; }
        public decimal Incomes { get; set; }
        public decimal Expenses { get; set; }
        public decimal Taxes { get; set; }
        public decimal Financial_Result { get; set; }
    }
}
