//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitterData
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tweet
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "The field is required")]
        [StringLength(100, MinimumLength = 3, ErrorMessage = "Text must be between {2} and {1} simbols")]
        public string Text { get; set; }

        public System.DateTime DatePosted { get; set; }

        [Required(ErrorMessage = "The field is required")]
        public string UserId { get; set; }

        public virtual AspNetUser AspNetUser { get; set; }
    }
}
